%% First we generate input data
birthdate = 20030509;    % Write the birth date on format yyyymmdd for oldest member in the group
format compact
[lambdavec,Tvec,cvec] = getSPOdata(birthdate);   %yyyymmdd  Do not use clear command or change the values of these variables

% -------------------------------------------------------------------------------------------------------------------
%% Marginal Allocation
% Question 1 should be answered in the report

cvec = cvec'; % transpose to column vector to use standard notation
svec = zeros(size(lambdavec))';

% Question 2 should described in the report, and submitted below
% Enter on the format EBO2 is total EBO after adding the spare part 
% Cost2 should be the cost of the added spare part
EBO2 = "to do";    
Cost2 = "to do";    %

Q2 = [EBO2 Cost2]; % Checking both at the same time in grader.

% Question 3, you should describe how the Marginal allocation is
% implemented in your own words in the report, and compute all efficient
% points.

% Question 4 should be answered in the report, with a figure and a table with
% all efficient points
% Furthermore, a table with first five efficient points should be submitted below
 
% Enter on the format EPtable = [ x0 EBO(x0) C(x0); x1 EB0(x1) C(x1); ... x4 EBO(x4) C(x4)]
% Where xj is the row vector with number of spare parts of each kind
% corresponding to the efficient points generated by the Marginal allocation algorithm
% EBO and C are the total values (scalars) for each allocation xj
EPtable = "to do";

function EBO = EBO_poisson_rec(mu, Smax)
    epsilon = 1e-12;
    pk = poisson_pmf_vec(mu, epsilon);   % P(X=k)
    F  = cumsum(pk);                 % F(k+1) = P(X<=k)

    EBO = zeros(Smax+1,1);
    EBO(1) = mu;                    % EBO(0) = mu

    for s = 1:Smax
        P_ge_s = 1 - F(s);          % P(X >= s)
        EBO(s+1) = EBO(s) - P_ge_s;
    end
end

function val = f_j(s_j, mu_j)
    % Return EBO_j(s_j) for a single LRU type
    EBO_vec = EBO_poisson_rec(mu_j, s_j);   % computes EBO(0..s_j)
    val = EBO_vec(s_j + 1);                 % index offset since EBO(0) is at position 1
end

function totalEBO = f2(s, mu)
    totalEBO = 0;
    for j = 1:length(s)
        totalEBO = totalEBO + f_j(s(j), mu(j));
    end
end