%% First we generate input data
birthdate = 20030509;    % Write the birth date on format yyyymmdd for oldest member in the group
format compact
[lambdavec,Tvec,cvec] = getSPOdata(birthdate);   %yyyymmdd  Do not use clear command or change the values of these variables

% -------------------------------------------------------------------------------------------------------------------
%% Marginal Allocation
% Question 1 should be answered in the report
cvec = cvec'; % transpose to column vector to use standard notation
svec = zeros(size(lambdavec))';

%Check that it's decreasing
mu = lambdavec .* Tvec;
EBOprev = inf;
for i=0:10
    svec = svec + ones(size(svec));
    EBO = f(svec, mu);
    diff = EBO - EBOprev;
    EBOprev = EBO;
end

%Check integer convexity
is_integer_convex(svec, mu)

%% Question 2.
n = length(lambdavec);
all_f = zeros(n,1);
for j = 1 : n
    s = zeros(n,1);
    s(j) = 1;
    all_f(j) = f(s, mu);
end
[EBO2, idx] = min(all_f);
fprintf('Best type: %d\n', idx)
Cost2 = cvec(idx);

Q2 = [EBO2 Cost2]

%% Question 3, you should describe how the Marginal allocation is
% implemented in your own words in the report, and compute all efficient
% points.

% Question 4 should be answered in the report, with a figure and a table with
% all efficient points
% Furthermore, a table with first five efficient points should be submitted below
 
% Enter on the format EPtable = [ x0 EBO(x0) C(x0); x1 EB0(x1) C(x1); ... x4 EBO(x4) C(x4)]
% Where xj is the row vector with number of spare parts of each kind
% corresponding to the efficient points generated by the Marginal allocation algorithm
% EBO and C are the total values (scalars) for each allocation xj
EPtable = "to do";


%% Functions
function output = EBO_i(s_j, mu_j)

    k_max = s_j + 30 + round(10 * mu_j);  % generous upper limit
    k = s_j+1 : k_max;

    % Compute EBO as sum of (k - s_j) * P(N = k)
    output = sum((k - s_j) .* poisspdf(k, mu_j));
end

% s = (s1, s2, ...) och mu = (lambda1 * T1, ...)
function output = f(s, mu)     % retunerar summan av alla f_j givet alla s_j och mu_j för varje reservdelstyp
    s_size = size(s);
    f = zeros(s_size(1), 1);
    for j = 1 : length(s)
        f(j) = EBO_i(s(j), mu(j));
    end
    output = sum(f);
end

function bool = is_integer_convex(svec, mu)
    delta_f_prev = -inf;
    diff = zeros(size(svec));
    for i=0:10
        splusone = svec + ones(size(svec));
        delta_f = f(splusone, mu) - f(svec, mu);
        diff(i+1) = delta_f - delta_f_prev;   

        svec = splusone;
        delta_f_prev = delta_f;
    end
    bool = all(diff >= 0);     % Check if all delta_f(s+1) are greater than delta_f(s)

    if bool
        disp("f is integer convex")
    else
        disp("f is NOT integer convex")
    end

end